### ISSUE TITLE
VirtualBox v7 Support?

### ISSUE THREAD

**Issue by pbarmak** [toptensoftware/VBoxHeadlessTray#35]
I love VBoxHeadlessTray! Any chance we'll get an updated version that supports VirtualBox 7.x?

**Comment by toptensoftware** [comment]
Yes it's on my todo list, but I'm super busy with another project right now.  In the meantime, each time VirtualBox comes out with a new version it usually VBoxHeadlessTray usually just needs to be rebuilt against the new SDK - so if you're up for doing that you could give it a try yourself.

**Comment by pseudex** [comment]
Hi,
I've recompiled it against the current SDK.
Unfortunately it is not easy. SimpleLib git link leads to new Version. V1 is needed instead.
With Visual Studio 2019 I got upgrade errors with SimpleLibAtlCom 9. Used 8 instead and renamed the lib files.
Also I had to set _WIN32_WINNT manually to WIN10.

```
#ifndef WINVER				// Allow use of features specific to Windows XP or later.
#define WINVER _WIN32_WINNT_WIN10		// Change this to the appropriate value to target other versions of Windows.
#endif

#ifndef _WIN32_WINNT		// Allow use of features specific to Windows XP or later.                   
#define _WIN32_WINNT _WIN32_WINNT_WIN10	// Change this to the appropriate value to target other versions of Windows.
#endif						
```

This I have also done for the SimpleLib projcets.

I did manage to compile but I'm not very pleased how this worked.
Here is the binary compiled with the current source code.
Since I'm not an expert with Visual Studio (I'm a PLC Programmer) take the compiled version with caution.

[VBoxHeadlessTray.zip](https://github.com/toptensoftware/VBoxHeadlessTray/files/10055531/VBoxHeadlessTray.zip)

**Comment by toptensoftware** [comment]
New build now available here: 
https://www.toptensoftware.com/vboxheadlesstray/
